OSCode-Community/OSCodeCommunitySite

- assets/css/style.css
initially it was simple back to button now its animated
> added animation in back to top button

- index.html
-Initially it is like this - 
-Updated to-
> Updated "Message Us" Button in Contact Us section which was antiquated

- assets/css/style.css
- chapters/chapter.html
- events/events.html
- index.html
Issue Solved: #31 
You can check:
> Ui Improvements

- assets/css/style.css
- index.html
> linked email and contact in the contact-us section

- events/events.html
Closes https://github.com/OSCode-Community/OSCodeCommunitySite/issues/20
Removed the console.log from the events page
> Removed console.log message from events page

- chapters/chapter.html
- events/events.html
Reverts OSCode-Community/OSCodeCommunitySite#75
> Revert "Updated Navbar of Chapters and Events Page"

- assets/css/style.css
Changed the design of the button making it more alive...hope it makes sense .Do check it out ! 
#Issue 54
> issue 54 resolved (Change in hover effect in **Why Choose Us?** section)

- assets/css/style.css
- Updated, it's  looking good and handy to use for users !  
**Before**
**After**
> Updated Corousel-Controls in Testimonials Section

- index.html
Reverts OSCode-Community/OSCodeCommunitySite#94
> Revert "Cursor pointer on hover in sponsors."

- .github/Pull_Req-template
- .github/issue_template/bug_report.md
- .github/issue_template/documentation.md
- .github/issue_template/feature_req.md
- .github/issue_template/question.md
> [Docs]:feat added issues and PR template

- README.md
Updated Readme file under #issue 89
> Update README.md #issue -89

- assets/css/style.css
- events/events.html
#issue 87 have been resolved ,added animation and color to the background of the Event Section.
Please do check it !
> added animated background for event section #issue 87

- assets/css/style.css
- index.html
Hi @peb-peb @akshathar-navada,
Made all necessary changes as per issue #45 raised.
-Added Glassmorphic effect (modified blur effect, earlier it was restricting mobile navbar layout)
-Responsive Navigation bar (earlier Navbar doesn’t work in mobile view) 
-Changed font in navbar
Now, Navbar works completely fine in mobile.
Screenshot After clicking on Navigation Icon (earlier):
Screenshot After clicking on Navigation Icon (now):
Glassmorphic effect:
> Improve visual structure of Navbar to make it more appealing and responsive

- assets/css/style.css
- index.html
Reverts OSCode-Community/OSCodeCommunitySite#107
> Revert "zoom in effect and italics"

- assets/css/style.css
> solved #70 added proper sizes

- chapters/chapter.html
Fixed the About nav item active error on chapter page.
> Fixed Active Navitem error on Chapters page

- assets/css/style.css
Improved responsiveness of landing page which occurred due to typing animation.
NOW
PREVIOUS
> Improved text typing animation's responsiveness

- policy.html
in policy.html its not matching the color theory 
now:
> title head background done purple

- assets/css/style.css
- index.html
**Contact Us Section Updated [GSSoC'23]**
This PR fixes #92 
- Added animations when user clicks on input field for better experience !
- Before
- After
> Updated Contact Us Section

- assets/css/style.css
By resolving this, User won't be confused upon selection among the carousel.
This PR fixes **#150** 
Please consider this contribution under **GSSOC (2023)**
> carousel selection colour changed

- assets/css/style.css
Reverts OSCode-Community/OSCodeCommunitySite#152
> Revert "carousel selection colour changed"

- assets/css/style.css
- chapters/chapter.html
- events/events.html
This PR fixes # #134 
You can check the following improvement
Adding blur navbar to the event section
remove too much border-radius and shadow
Chapter Section navbar
> Improvement event section card ui

- assets/css/style.css
#149 Made changes. now you can review it
Looks nice. I found some more bug in smaller sizes.. will create more issues later.
> fold view issue solved.

- .idea/workspace.xml
- README.md
> #175 Readme is Updated with badges

- assets/css/style.css
This PR fixes #135  Distorted logos in our sponsors & partners section.
**Before**
**After**
> Fixed distorted logos in our sponsors & partners section.

- .idea/.gitignore
- .idea/OSCodeCommunitySite.iml
- .idea/misc.xml
- .idea/modules.xml
- .idea/vcs.xml
- README.md
> Readme update

- chapters/chapter.html
- index.html
This PR fixes the error when redirecting to home from navbar in index.html and chapter.html
> Corrected the redirect link.

- assets/css/style.css
I have noticed that issue #163  is already updated by someone. So i updated the hover effects in the `events.html` and added some transition to it.
now box shadow is also highlighted below the card.
> Improved the card box shadow and added transition in it.

- assets/css/style.css
- chapters/chapter.html
- index.html
Made slight changes to footer UI so it is uniform across laptops of different aspect ratios
> Footer UI Improvement

- assets/css/style.css
- chapters/chapter.html
- index.html
Reverts OSCode-Community/OSCodeCommunitySite#227
> Revert "Revert "Footer UI Improvement""

- index.html
This PR fixes the home button form footer workable before it was not directing into the home page. Now its working.....
> made home button form footer workable

- index.html
The size of Youtube Icon is now increasing on hovering over it in the front page.
> YOUTUBE ICON SIZE NOW INCREASING ON HOVER

- chapters/chapter.html
This PR fixes #252 
The look of people image in chapter.html
> Fixed the look of people image in chapter.html

- assets/js/main.js
- chapters/chapter.html
Improved UI of search List and after deleting all characters from search bar now it doesn't display anything.
This PR fixes #201
Before:
After:
> search list issue fixed

- index.html
- package-lock.json
This PR fixes the centering issue of reach us section on smaller screen
> Centered the REACH US section [Fixes: #260]

- assets/css/style.css
- assets/js/main.js
- index.html
Given animation to text.
This PR fixes #239 
On clicking it animates like see-saw.
> Animated Home Page Text [GSSoC'23]

- assets/css/style.css
Message us button text color changed to black  <class=".msg-us">
hover animation has been added.
> Message us button fixed

- index.html
Added the hover animations to the statistics/numbers cards component on the web page.
* This PR fixes - #276
> Added animations to the number cards

- assets/css/style.css
- chapters/chapter.html
- index.html
This PR fixes #328 
As asked, the spacing between the socials and also with the copyright has been changed. Also I have made the footer orientation similar to other pages. I have add the screenshots of the home page and the events page for reference
This is the events page footer
And this is the current footer I changed for home page
> Fixed the Footer

- events/events.html
This PR fixes the improper redirection of Home, about and contact links in the navigation bar of events tab.I also fixed the improper highlighting of active navbar tabs.
Please check out the changes I made. Now the Home, About, Contact navigation bar links are redirecting to the respective pages properly. Also check the screenshot attached for better understanding.
> [Events section- navbar] - Adjusted improper redirection in navbar of events tab [GSSOC'23]

- assets/css/style.css
- index.html
Validation add in contact form by using JS.
Some font awesome icons used to make it look good.
@akshathar-navada  issue#148 resolved!!
> Improved Contact Section UI and add Validation too. issue#148 resolved

- assets/css/style.css
This PR fixes #339 
Initially photo was stable in About Us section, I've given floating animation to it.
Please do check and merge.
> Animation to Photo in 'About Us' section. [GSSoC'23]

- assets/css/style.css
Reverts OSCode-Community/OSCodeCommunitySite#340
> Revert "Animation to Photo in 'About Us' section. [GSSoC'23]"

- assets/css/style.css
I have made few changes in the file style.css, which have given more responsiveness to the content in other devices.
This PR fixes the issue #256 , Responsiveness of the content of the events section.
**before the changes**
**after the changes**
> The responsiveness in the content of the events section

- chapters/chapter.html
- index.html
This PR fixes the improper redirection of navigation bar buttons in the Chapters tab.
Now, I fixed that issue. The buttons in the chapters tab are properly redirecting to the respective pages. I also highlighted the current active tab. Please check out the screen shot for better understanding.
> [Chapters tab- Navbar] Corrected the improper redirections of the navbar links in the Chapters page

- assets/css/style.css
> #223 new features added

- chapters/chapter.html
- events/events.html
- index.html
Updated Redirection links in Navbar,Footer in home page,Redirection link in footer and its color.
This PR fixes #363 #364 #365 #366 #368 
- Updated Footer in home page.
- Updated 'About Us' Redirection link in Navbar of Home page and Events page.
- Updated 'Os-Code' Redirection link in footer in Chapters and Events.
- Updated Color of 'Os-Code' in footer in chapters page.
- Updated code lines of footer in Chapters page.
**Screentshots**
> Updated Redirection links in Navbar,Footer in home page,Redirection link in footer and its color.[GSSoC'23]

- assets/css/style.css
- index.html
I have added new features which is message section where user can ask new question if FAQ doesn't have that question. Also, UI is updated with card system and hover effect. 
This PR fixes issue #348 
This is for reference (Updated images)
> FAQ section updated with new features

- assets/css/style.css
- assets/js/main.js
- index.html
Reverts OSCode-Community/OSCodeCommunitySite#380
> Revert "Added google translator for people to connect across world"

- assets/css/style.css
i am solving by changed the css file#373
> changed the navbar chapter and event style

- assets/css/style.css
This PR contains the code of updated design of the "Numbers say it all!" section.
> Updated Design of "Numbers say it all!"

- README.md
Readme File Updated
This PR  Updates The Readme File
> File Updated

- assets/css/style.css
This PR contains the code of updated hover effected in "Reach us out through..." Section. 
Check the hover effect on first option named "Github".
> Updated Hover Effect of "Reach us out through..." Section

- chapters/chapter.html
- events/events.html
> Updated footer

- README.md
This PR fixes : added tech stack shields and badges in the readme
> Updated README.md added tech stacks

- chapters/chapter.html
- events/events.html
- index.html
This PR fixes #405
Site after adding button-
Original site without change-
> Added discord button in footer

- chapters/chapter.html
- events/events.html
- index.html
Reverts OSCode-Community/OSCodeCommunitySite#409
> Revert "Added discord button in footer"

- assets/css/override.css
- assets/css/style.css
- events/events.html
Built responsiveness in event section.
> responsive events

- assets/css/style.css
- index.html
Buttons arrows will appear on hovering 
without hover:
with hover:
AS  I earlier attached the video
> arrows appear on hovering 

- .vscode/settings.json
- index.html
> 435 is solved it the college section is added in contact

- assets/css/style.css
Reverts OSCode-Community/OSCodeCommunitySite#448
> Revert "[testimonial item class] Responsiveness Issue of text overflowing out of the placards solved"

- assets/css/privacy.css
- policy/policy.html
> Privacy fixed #450

- assets/css/style.css
- chapters/chapter.html
- events/events.html
> #460 issue solved

- assets/css/override.css
- assets/css/style.css
- index.html
click on mail or phone number to make a mail or call.
> #465 issue solved

- assets/js/main.js
- index.html
This PR fixes #462 
Previously when someone click on "OS-Code" logo it reload the page even when the user present in the index.html page.
Now the issue has been resolved
Now if you click on logo then it will not load the page and make the website more effective
https://github.com/OSCode-Community/OSCodeCommunitySite/assets/101205226/9a54363b-cd82-4f0d-b5df-2eed6493b33b
https://github.com/OSCode-Community/OSCodeCommunitySite/assets/101205226/59c4b868-ab31-41be-b1ea-12e9dc433883
> resloved the issue In Logo Link

- index.html
Updated "Contact Us" Button Redirection
This PR fixes #399 
> Updated Redirection Button

- assets/css/override.css
- assets/css/style.css
- events/events.html
- index.html
> #472 and #476 solved

- index.html
@akshathar-navada now check ! hope it will work fine.
> Contact section form validation done issue#424 resolved

- assets/css/style.css
- assets/css/whychooseusbutton.css
- index.html
This pull request aims to enhance the animation speed and visual appeal of the "Why choose us?" section and the "Numbers say it all!" section on the website and fixes #445 . Additionally, a margin end has been added between the navigation links and the contact section for better spacing and readability.
- Improved animation speed in the "Why choose us?" section to provide a smoother and more engaging user experience.
- Optimized animation timing and transitions in the "Numbers say it all!" section for a visually appealing effect.
- Added margin end between the navigation links and the contact Button to improve the layout and spacing.
Please review the changes and provide your valuable feedback.
> Animation Speed Improvement and Margins Enhancement

- index.html
contact form as it takes number value in name change the last name to college name and set a value of 10 in mobile input
> update the contact form

- assets/css/contact.css
- assets/css/style.css
- index.html
Reverts OSCode-Community/OSCodeCommunitySite#499
> Revert "Change in FAQS #494"

- assets/css/style.css
- index.html
Reverts OSCode-Community/OSCodeCommunitySite#491
> Revert "Updated "Join Us" Section"

- .vscode/settings.json
- events/events.html
This PR fixes #518 
It works perfectly now
https://github.com/OSCode-Community/OSCodeCommunitySite/assets/133862694/5b6b59c4-9224-4e4f-ab2f-f614869c1d01
> Fixed the navigation of footer in Events page

- assets/css/navbarUi.css
- assets/css/override.css
- assets/css/style.css
- index.html
#498 
Updated color and UI of navbar on Scrolling
> updated Navbar On scrolling #498

- assets/css/navbarUi.css
- assets/css/override.css
- assets/css/style.css
- index.html
Reverts OSCode-Community/OSCodeCommunitySite#536
> Revert "updated Navbar On scrolling #498"

- index.html
Reverts OSCode-Community/OSCodeCommunitySite#531
> Revert "added slider to accomplishments"

- index.html
Issue #506
This PR fixes - not redirecting user to Google map link of OS-CODE headquarter. 
I have added Google map location of OS-CODE headquarter in Footer section.
Please review the PR and let me know for any changes!
GSSOC'23 :)
> GMap link added in Footer Section

- assets/css/style.css
> Adding hovering effect on discord logo in footer

- chapters/chapter.html
- events/events.html
The About Us Link in Footer is fixed. It redirects to the about section in home page.
This PR fixes #523 
> About Us Link Fixed. Assigned #523

- .github/workflows/close_old_issues.yaml
> #540 Added

- .github/dependabot.yml
> #539 Added

- assets/css/style.css
- assets/js/main.js
This PR is Regarding issue #525.
I have fixed the position of nav-bar drop-down in mobile view and also fixed some comments spelling mistakes in main.js file
Thanks in Advance
> fixed navbar dropdown lists position in mobile view 

- assets/css/style.css
As being important for people to click to make it approachable made just a little larger
> get started and services button made little larger

- index.html
C
Contact Form Validation, Require Field added
> added validatation and required field

- assets/css/style.css
I have fixed the footer
This PR fixes #532 
> style.css updated to fix the footer

- README.md
- This is PR is about adding responsive dark/light logo, the logo will change according to the user's theme preference
- This PR fixes: #530 
- You can see the changes in below screenshot
- This is a retry of old PR: #543 
| LIGHT | DARK |
|  :-----:   | :-----:  |
| ![](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/92252895/75eba7d6-e7d9-4574-96b8-6080ad866cbb) | ![](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/92252895/dfa35981-37b6-4449-835f-08656b3a43a7) |
> 📝 Docs: Dark/Light Responsive Logo [RETRY]

- assets/css/style.css
- index.html
PR regarding
issue #592 
Made all the assigned changes to the CONTACT US button on top -
Before -
After -
> CONTACT US button improved [GSSOC'23]

- index.html
Closes #544
making scroll bar smoother using css in index.html file
Screenshot is not possible I make system smoother!
> add scrollbar smoother issue number - #544

- README.md
Closes #602
Added badges to ReadMe.md
> Added badges to ReadMe.md

- chapters/bit.html
- chapters/chapter.html
Closes #588 
Added new individual page as bit.html file to chapters page, linked to bangalore institute of technology.
> Added new individual page as bit.html file to chapters page, linked to bangalore institute of technology. [GSSoC'23]

- 404Error.html
Closes #598
I Remake the 404Error page into new level of UI 
https://github.com/OSCode-Community/OSCodeCommunitySite/assets/88212870/cbf5655a-19ee-44e2-83e7-be52c451ca43
> 404Error page next level!

- README.md
> I have updated README.md with several syntactical improvements

- chapters/chapter.html
Closes #619
Home link working
Thank you
> home link working#619

- chapters/chapter.html
- events/events.html
Closes #620 
on event page community links are working
Please see to it.
Thank you
> community links working on event page

- assets/css/style.css
Closes #610 
Earlier, the accomplishment section was not responsive. I have made the necessary changes and added the media queries to make the section responsive.
Before:
After:
Please review the pull request.
> Made Accomplishment Section Responsive [Closes #610]

- assets/css/contactform.css
- index.html
Closes #629  
#629
- [X ] I have linked the PR to the correct issue.
- [X ] I have read the [Contribution Guidelines](https://github.com/OSCode-Community/OSCodeCommunitySite/blob/master/CONTRIBUTING.md)
- [X ] I have built and tested the changes, and they do not break or show any errors.
<!--
Thank you for contributing to OSCodeCommunitySite!
> contact form college section is added

- assets/css/faq.css
- index.html
Closes #627 
- Fixed paths of gif, CSS file and image in assets/css/faq.css and index.html
- Added compatible bootstrap JS CDN in index.html.
- assets/css/faq.css
- index.html
[demo.webm](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/130365071/6b5ab73e-a63a-4ffd-a7a4-22232daf3d8f)
Please review this PR.
Thanks
> Fixed Errors and warnings on browser's console #627

- assets/css/chapter.css
Closes #595 
I have added hover effect for increasing font size,and changing color when hovered
Earlier
https://github.com/OSCode-Community/OSCodeCommunitySite/assets/127978268/e005d91d-411f-49ce-8b77-710ca6683d1e
now
https://github.com/OSCode-Community/OSCodeCommunitySite/assets/127978268/ba0cc1a4-241f-4202-bbf8-36ac332389f1
> Hover Effect on each item in college chapter added

- .github/ADD_ISSUE.yml
Closes issue number  #633 
Added new issue label.
> Added new issue label

- assets/css/events.css
**Solved Issue no #636** 
Enhancing the view of event page. 
I made a valuable contribution to the (events) page of the project. As a part of this initiative, I forked the repository and worked on enhancing the user interface of the (events) page of the website.
**Screenshots**
**work** 
I focused on improving the visual appeal and overall user experience by adding CSS styles to the Events page. With careful consideration of the existing design and user feedback, I implemented various CSS enhancements to make the page more engaging and user-friendly.
**Some of the key changes I made include:**
Typography: I refined the typography by selecting appropriate fonts, sizes, and line heights to improve readability and create a consistent visual hierarchy.
Color Scheme: I revamped …
> Enhanced the view of images of the 'events' page of the website

- assets/css/contactform.css
Closes #609 
Earlier, the message field did not have the hover effect. I have added the hover effect on the message field also to make the page identical.
Please review the code.
Before:
After:
> Update contactform.css [Closes #609]

- chapters/chapter.html
Closes #639 
Updated Design which was not much good or attractive
> Fixed design

- index.html
Close #654
Previously on hovering above the discord icon ,it was not increasing in size in the footer of front-page. Now it is increasing in size on hovering. Now can it be merged?
> Size of discord icon now increasing on hovering in the footer of front-page

- assets/css/style.css
Closes #655
I have changed the styling of the "upskill students" ,so that now it matches the color of website and looks better.
On hovering
> "Upskill students" styling changed

- assets/css/style.css
Reverts OSCode-Community/OSCodeCommunitySite#664
> Revert ""Upskill students" styling changed"

- index.html
Reverts OSCode-Community/OSCodeCommunitySite#663
> Revert "Size of discord icon now increasing on hovering in the footer of front-page"

- assets/css/style.css
- index.html
> Changd The Color of Hyperlink

- index.html
Closes #654
I hacve solved the issue.Now the discord icon is increasing in size on hovering .
Before hovering
After hovering
> Discord icon hover issue resolved

- assets/css/style.css
- index.html
Hey @akshathar-navada , I have made all the necessary changes just the way you wanted.
> Added hovering effect to the navbar

- assets/css/override.css
- assets/css/style.css
- chapters/chapter.html
- index.html
Reverts OSCode-Community/OSCodeCommunitySite#722
> Revert "fixed issue #721"

- assets/css/contactform.css
- index.html
Closes #issue_number 
The overlaping issue has been resolved successfully, the responsiveness is working correctly.
> the contact section has been fixed

- login/login.html
- signup/signup.html
Closes #737
In the navbar, the links (home, blogs, events etc.) were not working in login and signup page.
( https://www.oscode.co.in/login/login.html )
( https://www.oscode.co.in/signup/signup.html )
Raising this PR under gssoc23
> [gssoc23] login and signup pages navbar links added

- index.html
Reverts OSCode-Community/OSCodeCommunitySite#742
> Revert "Nav Bar Modification in Header Section"

- assets/css/style.css
- index.html
Closes #issue_number 
Fixes:#558
###Changes:
-Change in the css of why choose us as during the check of responsiveness it leads to overlap
-Changes in the css of contact us as the p tag of email and phone numbers overlap
###Proof of Work:
The earlier behaviour of the why choose us
Updated behaviour:
The earlier behaviour of contact us
The changed behaviour:
> Changes in css of why choose us and contact us

- assets/css/about.css
#735
Increasing length of line under heading on hover to make website look more alive.
[Screencast from 14-06-23 11:51:46 PM IST.webm](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/98320971/dbbd7933-e143-4240-9a27-ca5f50daa83e)
- [✔️] I have linked the PR to the correct issue.
- [✔️] I have read the [Contribution Guidelines](https://github.com/OSCode-Community/OSCodeCommunitySite/blob/master/CONTRIBUTING.md)
- [✔️] I have built and tested the changes, and they do not break or show any errors.
> Adding Hover Effect to the <hr> line under heading to make website look more alive. #735

- assets/css/login.css
- assets/css/signup.css
- login/login.html
- signup/signup.html
Closes #738 
The UI of login page and signup page is revamped and made responsive.
( https://www.oscode.co.in/login/login.html )
( https://www.oscode.co.in/signup/signup.html )
I want to create this PR under gssoc23
> [gssoc23] login and signup pages UI revamped

- assets/css/style.css
- chapters/css/styles.css
Closes #702 
The Social Icon issue #702 in both the Index.html and bit.html pages has been resolved. The hovering effect has been removed from the icons on the index.html page, and the hovering effect and icon color have been fixed on the bit.html page.
**bit.html**
**Before :** 
**After :**
- [✅] I have linked the PR to the correct issue.
- [✅] I have read the [Contribution Guidelines](https://github.com/OSCode-Community/OSCodeCommunitySite/blob/master/CONTRIBUTING.md)
- [✅] I have built and tested the changes, and they do not break or show any errors.
> Fixed Social Icons [Index.html & bit.html]

- assets/css/resetpass.css
- resetpass/resetpass.html
- resetpass/resetpass.js
- signup/signup.html
Closes #740 
While clicking forgot password? in login page, it redirects to this reset password page.
Reset password page is created and linked.
I want to create this PR under gssoc23
> [gssoc23] Reset Password Page Created

- index.html
> linked service page

- assets/css/faq.css
Closes #710  
- **Change the Font Weight From 400 to 900 for Improving Better Attention on FAQ List** 
> **Code Change Screenshot**
> **After Changing Font Weight FAQ List Look Like This Screenshot**
- **Change the ` Font Weight` From `400 to 900` like `font-weight: 900`;to Improve Much Attention on FAQ List.**
> Update Font Weight FAQ List

- services.html
> explore button and testimonials name updated

- assets/css/join_us.css
- assets/css/style.css
- index.html
> fixed #764

- assets/css/counts.css
- assets/css/style.css
This PR contains the updated code for the consistent "Hover Effect" in all sections of the website. This PR is the result of the following issue:
Consistent Hover Effect In All Sections Of Website #771
Closes #771
Consistent hover effect in all sections of the website.
**Numbers say it all Section** 
**Accomplishments Section**
**Join Us Section**
**Testimonials Section**
Kindly share your valuable feedback or any suggestions for more good improvement in the following issue.
> Consistent Hover Effect In All Sections Of Website 

- assets/css/style.css
Closes #753 
[Screencast from 15-06-23 07:06:13 PM IST.webm](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/98320971/96627cf4-a76c-4afc-84b4-df96efe6acdc)
- [✔️] I have linked the PR to the correct issue.
- [✔️] I have read the [Contribution Guidelines](https://github.com/OSCode-Community/OSCodeCommunitySite/blob/master/CONTRIBUTING.md)
- [✔️] I have built and tested the changes, and they do not break or show any errors.
> KnowUs Improved #753

- assets/css/style.css
Closes #698
Fixed the issue for a navbar on the large screen.
> Fixed navbar for large screen

- assets/css/counts.css
- assets/css/style.css
Reverts OSCode-Community/OSCodeCommunitySite#773
> Revert "Consistent Hover Effect In All Sections Of Website "

- assets/css/services.css
- services.html
> os code services list style altered to square

- assets/css/style.css
Reverts OSCode-Community/OSCodeCommunitySite#777
> Revert "Fixed navbar for large screen"

- assets/css/about.css
- index.html
Closes #666  
Changed the alignment of the heading and also fixed the position of image and paragraph
please review my work 
- [. ] I have linked the PR to the correct issue.
- [ .] I have read the [Contribution Guidelines](https://github.com/OSCode-Community/OSCodeCommunitySite/blob/master/CONTRIBUTING.md)
- [ .] I have built and tested the changes, and they do not break or show any errors.
> #666 whoweare(UI Improve)

- assets/css/login.css
- assets/css/signup.css
- login/login.html
- login/login.js
- signup/signup.html
- signup/signup.js
Issue closed: #785 
Sign in page
Sign up page
> Adding show password option

- assets/css/style.css
- index.html
> Changed the transparency of navbar for the color to look good.
> fixed issue #783

- assets/css/about.css
- assets/css/style.css
- index.html
> fixed issue #796

- assets/css/services.css
- services.html
> Made service section responsive

- assets/css/about.css
- assets/css/style.css
Image is correctly aligned in any device
> Fixed issue #793

- assets/css/style.css
Closes #801 
[Screencast from 20-06-23 03:27:44 PM IST.webm](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/98320971/ca2f49a1-449e-4733-a225-73bec947e224)
- [✔️] I have linked the PR to the correct issue.
- [✔️] I have read the [Contribution Guidelines](https://github.com/OSCode-Community/OSCodeCommunitySite/blob/master/CONTRIBUTING.md)
- [✔️] I have built and tested the changes, and they do not break or show any errors.
> Footer responsivenss

- assets/css/services.css
Closes #issue_number 
https://github.com/OSCode-Community/OSCodeCommunitySite/assets/119532943/b436ccbd-f1e9-48ee-add6-9de7366c058a
> ADDED hovering transition to button

- assets/css/style.css
- index.html
@akshathar-navada I have changed the style and opened this PR as per your instruction under Gssoc 2023.
Do check it out ,if any changes req. : |)
#763 
Closes #
> Changed the sytle of buttons(get started,service) in home page  issue-763

- assets/css/style.css
- index.html
Reverts OSCode-Community/OSCodeCommunitySite#835
> Revert "Changed the sytle of buttons(get started,service) in home page  issue-763"

- assets/css/about.css
Closes #815 
Improved the alignment of the image in large view
- [. ] I have linked the PR to the correct issue.
- [. ] I have read the [Contribution Guidelines](https://github.com/OSCode-Community/OSCodeCommunitySite/blob/master/CONTRIBUTING.md)
- [. ] I have built and tested the changes, and they do not break or show any errors.
> Alignment of Image in large View

- assets/css/chapter.css
- chapters/chapter.html
Closes #
Hover effect to the Title in Chapters Page [GSSoC'23]
> Hover effect to the Title in Chapters Page [GSSoC'23]

- .github/ISSUE_TEMPLATE/bug_report.md
> initial commit

- .github/ISSUE_TEMPLATE/bug_report.md
Reverts OSCode-Community/OSCodeCommunitySite#844
> Revert "initial commit"

- .github/workflows/linting.yml
* Closes - #845 
Added the prettier linter to ensure proper and uniform linting of the codebase.
> Added the Linter workflow

- events/event.css
- events/events.html
> Event page UI

- .vscode/settings.json
- chapters/chapter.html
Closes #892 
Fixed the naigation of the chapters page to about and contacts section
> Fixed navigation of the Chapters Page

- index.html
- Added primary meta elements for html, which plays a crucial role in providing additional information about an HTML document. 
- They help with specifying the character encoding, defining the viewport for responsive design, setting the page title, and providing page descriptions. 
- They assist search engines, browsers, and other web applications in understanding and processing the webpage's content effectively.
> add: primary meta elements for html  🚀

- contact/contact.html
Closes #912 
Added Navigation to the navbar in the Contact Us Page
https://github.com/OSCode-Community/OSCodeCommunitySite/assets/133862694/50565ab2-bd90-456a-9afd-3218acc8d0c8
> Added navigation to Contact Us page

- login/login.html
- resetpass/resetpass.html
- resetpass/resetpass.js
- signup/signup.html
Issue solved: #885 
Now if you click the "OsCode" it should be redirected to the home page
https://github.com/OSCode-Community/OSCodeCommunitySite/assets/94003231/71fcd0cb-6eb7-4004-a509-2625591bdcc9
> Add back button and show password button

- assets/css/about.css
- assets/css/style.css
- chapters/css/styles.css
- events/events.html
- index.html
Closes #926 
**Issue Title:** Enhancement of the menu links of Navigation bar & elimination of navigation toggler
1. **CSS properties of Navigation menus**(or links) changed in `assets/css/style.css` file to enhance their visibility.
2. **Mobile navigation toggle** icon removed from the navbar by commenting it out in the `index.html` file.
*After enhancement of navigation links:*
*After removing the navigation toggler:*
https://github.com/OSCode-Community/OSCodeCommunitySite/assets/103258259/0f1e52fd-666b-46ba-a697-4d358fb4ebdd
Kindly review the PR and merge it so that I can contribute to your project under GSSoC'23.
> Navigation Links enhanced and Toggler icon removed

- assets/css/about.css
- assets/css/style.css
- assets/js/main.js
- chapters/css/styles.css
- events/events.html
- index.html
- login/login.html
- resetpass/resetpass.html
- resetpass/resetpass.js
- signup/signup.html
Close #939 
Fixed the entire home page as it was distorted earlier by some pull request
https://github.com/OSCode-Community/OSCodeCommunitySite/assets/133862694/1cdab26d-c4c2-4aa2-8387-619d43d36659
> Entire home page fixed

- chapters/chapter.html
- index.html
Fixed #945
https://github.com/OSCode-Community/OSCodeCommunitySite/issues/945
I have a navbar issue!
> Fixed Navbar issue

- assets/css/style.css
Closes #932
The paragraphs are appropriately spaced and the same font is consistently used throughout.
- ✅ I have linked the PR to the correct issue.
- ✅ I have read the [Contribution Guidelines](https://github.com/OSCode-Community/OSCodeCommunitySite/blob/master/CONTRIBUTING.md)
- ✅ I have built and tested the changes, and they do not break or show any errors.
> fixed margin and font

- assets/css/style.css
Closes #938
Fixed the padding between elements and adjusted the buttom
> Fixed the Header

- assets/css/style.css
- index.html
Closes #980 
I added chatbot feature on website
> Add Chat bot

- events/events.html
Closes #975
Added login page icon to the Events page and linked it accordingly. It was previously not there
> Added login page icon to the Events page

- chapters/bit.html
- chapters/chapter.html
- contact/contact.html
- events/events.html
- index.html
- services.html
Closes #976
Added github to footer or all pages. Also added their navigation to this github repository
> Added github to footer or all pages

- assets/css/style.css
Closes #1026 
- [X ] I have linked the PR to the correct issue.
- [ X] I have read the [Contribution Guidelines](https://github.com/OSCode-Community/OSCodeCommunitySite/blob/master/CONTRIBUTING.md)
- [X ] I have built and tested the changes, and they do not break or show any errors.
> updated - now home page is not broken

- assets/css/about.css
- assets/css/services.css
- assets/css/style.css
- services.html
Solves #973 
fixes: 
Navbar 
remove horizontal scrollbar
make the service page responsive
> Adding navbar and make the page responsive

- assets/css/about.css
- assets/css/contact.css
- assets/css/services.css
- assets/css/style.css
- contact/contact.html
- services.html
> Make contact page responsive

- chapters/chapter.html
Closes #1036
links are now taking to respective page 
https://github.com/OSCode-Community/OSCodeCommunitySite/assets/96969496/a825e2f2-afd7-47e6-b94e-11d99bbc6677
> links are repair

- assets/css/faq.css
- index.html
Closes #1035 
faq text color updated
> text color updated

- README.md
Closes ## #1033 
Added a more comprehensive method to install the necessary dependencies and open a pr
> Update README.md to make it more comprehensive

- chapters/chapter.html
- contact/contact.html
- contributors/contributor.html
- contributors/style.css
- contributors/style.js
- events/events.html
- index.html
solves #1017 
Also, it was responsive
> Added contributor page

- assets/js/main.js
Closes #1042 
https://github.com/OSCode-Community/OSCodeCommunitySite/assets/96969496/16b3875e-2fc6-46d7-a72c-c797744bb4f9
> back to top arrow updated

- assets/css/gallery.css
- assets/gallery.html
- index.html
I have created a seperate page for the gallery section .
Lemme know if you want any other changes.
Closes #1041
> gallery section updated

- assets/css/services.css
- services.html
Solves #1018 
@Vaishnavi-Patil2211 can you please check
> Add responsiveness

- services.html
Closes #1050
oscode logo link updated
> oscpde logo link updated

- assets/css/services.css
> card updated

- contributors/contributor.html
- contributors/style.css
- contributors/style.js
I have modified the Ui of  the contributors page .Please check and lemme know if u wanna any other changes.
Closes #1068
> Contributor page modified

- assets/gallery.html
- contact/contact.html
- events/events.html
- index.html
#Done changes in index.html 
#added link of event as it had an issue
> Added whatapp and added event link in index.html

- assets/css/style.css
- index.html
Fixed #1044 
Closes #1044 
- Added hover effect for GitHub link in the footer section in ` assets/css/style.css `
- And formatted ` index.html `, removed extra space to improve readability.
https://github.com/OSCode-Community/OSCodeCommunitySite/assets/113251342/befdd4ec-8eb6-46d8-9ba6-9d5fdf1b28cd
- Let me know if any adjustments are required.
- Can you please add the `gssoc` label and the issue `level` acc to you.
> Fix issue #1044: Added hover effect on github link

- assets/css/login.css
- assets/css/override.css
- assets/css/resetpass.css
- assets/css/signup.css
- assets/css/style.css
- firebase/firebase.js
- login/login.html
- login/login.js
- signup/signup.html
- signup/signup.js
Closes #986 
Hey @Vaishnavi-Patil2211 I have successfully added Firebase authentication to the website. I have removed the variables for the Firebase file for security purposes. You can create a project in Firebase and add the variables in that file.
> Added firebase authentication to the website

- assets/css/contact.css
- contact/contact.html
Updated the Contact Us Page .
@Vaishnavi-Patil2211  Please review and inform me if you wanna any other changes.
Closes #1074
> Contact Us Page Modified

- assets/css/style.css
- index.html
Closes #1086 
before:
without hover:
hover:
- [ X] I have linked the PR to the correct issue.
> Improve the social media icons

- assets/css/join_us.css
- index.html
> Improve the contact us section

- index.html
Closes #1084 
Hey @Vaishnavi-Patil2211 I have fixed the bug present in the navbar in the index.html file. The vents page was not accessible from the main page. Now it can be accessed. Please review my pr and merge it. Thank you!
> Removed bug from navbar in index.html file

- assets/css/counts.css
- index.html
> Improved the counts section

- assets/css/contact.css
- index.html
> Improved Contact us form 

- assets/css/client.css
> Improve hover effect in clients section

- assets/css/style.css
- index.html
Closes #1092
i have added tooltips to the footer social media icons
> footerstylingchange

- resetpass/resetpass.html
- resetpass/resetpass.js
@Vaishnavi-Patil2211 solves #1081 
> Forgot password page add show password button

- chapters/chapter.html
Closes #1108 
footer navbar links updated  and logo added
> links updated

- login/login.html
- signup/signup.html
@Vaishnavi-Patil2211 solves #1083 
> Edge cases

- assets/css/gallery.css
- assets/css/style.css
- index.html
> benefits updated

- assets/css/style.css
Closes #1103 
before--
---
now:--
> Footer And contact us responsive

- assets/css/style.css
- assets/gallery.html
- chapters/chapter.html
- events/events.html
- index.html
Closes #1131
i have added the logo to all the pages like home chapters and which ever have the footer I have added them.
i have added the images to the footer and changed the footer elements to when we hover on them they will get underlined with some transition.
> addedlogoimage

- events/event.css
- events/events.html
@Vaishnavi-Patil2211 , I have changed the cards to flippers.So,please review and merge the PR.
Closes #996
> Events section card modified

- 404Error.html
- contact/contact.html
- services.html
Closes #1155
i have added logos to error page and services page and also to contact page in footer
in services page
in contact page
in error page
> logossettoallpages

- assets/css/chapter.css
- chapters/chapter.html
- chapters/css/styles.css
@Vaishnavi-Patil2211 solves #1124 
> Add hover effect

- README.md
Closes #863 
The port number in README.md was 5000, while the project ran on port 3000. This pr corrects the documentation.
> [Fixes: 863] Updated The Port Number

- contact/contact.html
- contact/contactstyle.css
- contributors/contributor.html
Closes #1156 and #1153 
the both issue get resolved the bottom to top push button and the contact us page 
- [X ] I have linked the PR to the correct issue.
- [X ] I have read the [Contribution Guidelines](https://github.com/OSCode-Community/OSCodeCommunitySite/blob/master/CONTRIBUTING.md)
- [X ] I have built and tested the changes, and they do not break or show any errors.
> contact section is updated

- assets/css/contact.css
- index.html
Closes #1132 
when we are typing the text was coinciding with what we are typing I changed it.
> contactusplaceholder

- assets/gallery.html
Closes #1171
changed the title of gallery to gallery from events
> titlechanged

- assets/css/chapter.css
- chapters/chapter.html
@Vaishnavi-Patil2211 Can you please check my pr
solves #1122 
> Chapters page is not responsive

- assets/css/style.css
- contact/contact.html
Closes #1133
i have changed the styling of the contacts and also the footer social icons gap
> contactusstyling

- assets/css/style.css
- chapters/bit.html
- chapters/css/styles.css
Navbar Modified.
@Vaishnavi-Patil2211 ,please check and merge .
Closes #1150
> Navbar of the BIT page modified

- assets/css/style.css
Closes #1180
i have placed the logo a little bit above so that footer looks good
> madefooterlogoatcorrectplace

- assets/css/contact.css
- contact/contact.html
Closes #1183 
changed the contacts page footer and also the page your numbers were not visible changed that color to white
> changedstylingofcontactpage

- contact/contact.html
Closes #1199 
I have added the tooltip on the contact page also I have changed the color of WhatsApp to green before it was blue which was a bug
> contactpagefooter

- assets/css/join_us.css
- Fixed background color with bad contrast text for button element
|BEFORE|AFTER|
|:---:|:---:|
| ![Screenshot 2023-07-24 at 22-20-50 OS Code](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/92252895/5c386547-284d-455d-9175-ef8f88e909f5) |![Screenshot 2023-07-24 at 22-20-22 OS Code](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/92252895/f0c472ed-b769-4610-96d9-9ea9bb8c16c1) |
> fix: bad background of button 🛠

- assets/css/signup.css
- signup/signup.html
Closes #1182
Add empty validation on form
Validation add for valid email
Error message shown below of each fields
@Vaishnavi-Patil2211 issue#1182 resolved
> Add validation on signup form

- assets/gallery.html
Closes #1195 
I have added the tooltip on the gallery page also I have changed the color of WhatsApp to green before it was blue which was a bug
> gallerypagesocialiconsinfooter

- assets/css/style.css
- index.html
> Fix the Font

- policy/policy.html
> Added move to top button 

- chapters/bit.html
- chapters/css/styles.css
@Vaishnavi-Patil2211 ,footer updated ,please check and merge the PR.
Closes #1149
> Footer updated for BIT Page

- assets/css/privacy.css
- policy/policy.html
Closes #1114 
I have made the privacy page responsive
> Make Privacy Page Responsive

- services.html
Closes #1201
i have added the WhatsApp logo in services page
> whatsapplogoadded

- index.html
Closes #1212
i have added the favicon to the home page
> faviconadded

- assets/css/style.css
> Responsive footer

- index.html
Closes #1225
i have added the sponsors images
> addedimagepaths

- 404Error.html
Closes #1197
i have added the go home button in error page
> addedgohomebutton

- index.html
Closes #1203 
Wrong image extensions were mentioned in homepage, therefore images were not showing.
This pr solves this issue.
Now images are visible
> [Fixes #1203] Fixes Image Issue in Home Page

- assets/css/chapter.css
- chapters/chapter.html
@Vaishnavi-Patil2211 , I have updated the UI of the chapters page card , please check and merge.
Closes #1210
> Chapters Page cards UI updated

- policy/policy.html
Closes #1237 
I have fixed the missing images.
> Add Images to policy page

- contributors/contributor.html
> Added Footer to Contributors Page

- assets/css/signup.css
- signup/signup.html
@Vaishnavi-Patil2211 ,I have improved the UI of the SIgnUp Page ,please review and merge.
Closes #1227
> SignUp Page Css Modified

- contributors/contributor.html
- contributors/style.css
Closes #1249
i have changed the copyright of contributor page as home page and made it interactive in phone mode also
> copyrightincontributorpage

- assets/css/login.css
- login/login.html
@Vaishnavi-Patil2211 ,SignIn page UI modified , please review and merge.
Closes #1226
> SignIn page modified

- 404Error.html
Closes #1243
i have added the favicon for error page
> addedfaviconinerrorpage

- contributors/contributor.html
Closes #1247
i have placed the logo of footer at correct place
> addedlogoatcorrectplace

- contributors/style.css
- contributors/style.js
> Improved the contributor cards

- assets/css/services.css
- services.html
@Vaishnavi-Patil2211 ,carousel added to the our services section ,please review and merge the PR.
Closes #1251
> Carousel added to our services module

- events/event.css
- This PR is about fixing the alignment issues of two elements on Events Page.
||B E F O R E|
|:----:| :----: |
| **ELEMENT 1**| ![Screenshot 2023-07-26 at 18-30-11 OS-CODE Events](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/92252895/e526911a-e442-416e-82f5-c6bc9f9040ea) |
| **ELEMENT 2**|  ![Screenshot 2023-07-26 at 18-30-28 OS-CODE Events](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/92252895/910867f1-8372-42f5-be5a-b069623edcfb) |
||A F T E R |
|:----:| :----: |
| **ELEMENT 1**| ![Screenshot 2023-07-26 at 18-26-51 OS-CODE Events](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/92252895/d79ba4be-682c-4d51-98a2-ba0752c1a698) |
| **ELEMENT 2**|  ![Screenshot 2023-07-26 at 18-27-18 OS-CODE …
> fix: incorrect alignment of elements on events page 🛠

- assets/css/client.css
- Added 3D Rotating effect for Brand Logo's on Sponsers Section of OS-CODE Website
https://github.com/OSCode-Community/OSCodeCommunitySite/assets/92252895/3765cab6-80e0-4fec-9a1a-63fd637be3d9
> feat: add 3d rotate feature for brand logos on sponsers section ✨

- login/login.html
> updated logo

- assets/css/chapter.css
- chapters/chapter.html
@Vaishnavi-Patil2211 , restored  the footer of the chapters page ,please check and review
Closes #1252
> Chapters Page footer 

- assets/css/login.css
- login/login.html
- login/login.js
Closes #1284
Add empty validation on form
Validation add for valid email
Error message shown below of each fields
@Vaishnavi-Patil2211 issue #1284 resolved.
> validation added on login form

- assets/css/login.css
- login/login.html
Closes #1287 
[screen-capture.webm](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/85815172/74d5e888-4dae-482c-a81e-704c51b472a0)
> Style: improve the Styling of Btn ✨

- firebase/firebase.js
- login/login.js
- login/profile.html
Closes #1283 
I have successfully implemented Google Login functionality and created a Profile Page for the OSCODE Community Website. This enhancement aims to enhance user experience and provide more personalized features for our community members.
Adding Google Login and Profile Page to OSCODE Community Website
Features Implemented:
1. **Google Login**: Users can now sign in to the OSCODE Community Website using their Google accounts. This integration allows for a seamless login experience and simplifies the registration process for new users.
2. **Profile Page**: After logging in, users have access to their personalized Profile Page, where they can view and manage their account information. The Profile Page provides users with the following details:
- User's Name: Displayed on the …
> Adding Google  FIREBASE Login and Profile Page to OSCODE Community Website

- assets/css/chapter.css
- Revamped the cards design to improve the UI which matches the site's theme.
|BEFORE|AFTER|
| :----: | :-----:|
|![Screenshot 2023-07-26 at 20-30-11 OS-CODE Chapters](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/92252895/9d604a09-2267-4bdb-8ac9-2a64d7ed9745) | ![Screenshot 2023-07-26 at 20-27-19 OS-CODE Chapters](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/92252895/b363aede-7ef7-4e6d-bf7d-8f2f561fdcb9) |
> feat: revamp the card designs on chapter page 🪄✨

- 404Error.html
Closes #1271 
i have added the logoname
> logonameadded

- contributors/contributor.html
Closes #1299
i have added the font size to the contributor text
> contributortextchanged

- policy/policy.html
- Fixed the missing preloader for Privacy policy page
> fix: missing preloader for privacy policy page 👷🏻🛠️

- contributors/contributor.html
- contributors/style.css
- Revamped the card design on contributors page, removed unwanted gradients during hover.
- Cards were revamped as per the OS-CODE Theme color, so our site will have a consistent color patterns around the web which improved the overall UI & UX.
|B E F O R E| A F T E R|
|:----:|:----:|
| ![Screenshot 2023-07-27 at 16-40-11 OS-CODE Contributor](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/92252895/4904a580-7f6e-45e4-8c32-0fcb36119c26) | ![Screenshot 2023-07-27 at 16-39-46 OS-CODE Contributor](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/92252895/0c1dda2a-4031-4877-8c14-f184f28c6e37) |
> feat: revamp cards design on contributors page 🪄✨

- index.html
Closes #1310
i have added the image in our accomplishments
> addedimageindex

- events/events.html
- index.html
Closes #1266 
There was a p tag in each event card which needs to be used only when there is some content related to event. And for now sample text was present in that tag which was not required, so I removed that.
> [Fixes: #1266] Resolved Bug in event cards

- assets/css/services.css
Closes #issue_number #1059
adding the style for responsive website
> fix: website is not responsive #1059

- assets/css/override.css
- assets/css/style.css
- index.html
> Fixed mobile view of Achievement section

- README.md
- Made GSSOC Banner Responsive to Light/Dark Mode for Repository Readme.
<table border="2">
<tr>
<th>O R I G I N A L</th>
</tr>
<tr>
<td>
<table border="1">
<tr>
<th>LIGHT MODE</th>
<th>DARK MODE</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
</td>
<td>
<table border="1">
<tr>
<th>LIGHT MODE</th>
<th>DARK MODE</th>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
</td>
</tr>
</table>
> docs: add dark/light responsive gssoc banner ✨

- assets/css/client.css
Closes #1318
**This pull request aims to enhance the "client.css" file by refactoring the existing CSS code and implementing best practices to improve maintainability, readability, and performance. The changes have been made with careful consideration of the HTML structure and are intended to enhance the visual presentation and responsiveness of the website.**
**The changes have been extensively tested on various devices and screen sizes to ensure proper responsiveness and consistent appearance across different platforms. The layout and functionality of the website remain unaffected by the CSS modifications.**
> refactor the client.css ✨

- assets/css/about.css
Closes #1316 
I have Refactor about.css page Change i have mention in the issue
> refactor the about.css CSS code. ✨

- assets/css/style.css
- chapters/chapter.html
Closes #1341
i have changed the WhatsApp color logo
> colorofwhatapps

- contributors/contributor.html
- contributors/style.css
Closes #1346
i have added the copyright
> copyrightchanged

- .husky/commit-msg
- commitlint.config.js
- package.json
Closes #1337
I have init the Commit Lint and also install the Husky which is GitHub hook which is check the commit is Conventional not.
> feat: init commit lint✨

- index.html
- Fixed the broken navigational link for Events page which can be found on OS-CODE's Homepage
- And additionally, removed unwanted inline styles from the navigational links to improve code readability.
> fix: incorrect navigational link for events page on homepage  🧑🏻‍🏭🛠

- chapters/chapter.html
- contact/contact.html
- contributors/contributor.html
- events/events.html
- index.html
- login/login.html
- login/profile.html
- policy/policy.html
- resetpass/resetpass.html
- signup/signup.html
Closes #1328 
I'm thrilled to present my latest contribution to our community website - the OSCODE COPILOT, an innovative AI-powered voice and text assistant designed to enhance your browsing experience like never before!
1. **Seamless Voice Interaction**: Say goodbye to conventional navigation! The OSCODE COPILOT allows you to interact with our website using natural language commands. Simply speak, and let the AI take care of the rest.
2. **Smart Text Assistance**: Have a question while browsing through code snippets? The OSCODE COPILOT is here to help! It can intelligently analyze your text queries and provide relevant suggestions and resources.
3. **Personalized Recommendations**: The AI assistant learns from your browsing patterns and offers personalized recommendations, making it …
> "Introducing the OSCODE COPILOT: Your AI-Powered Voice and Text Assistant 🚀"

- assets/css/login.css
- assets/css/signup.css
> Added visibility

- contact/contact.html
> Fixed the logo position

- .prettierrc
- package.json
Closes #1339 
**This pull request introduces the integration of Prettier, the code formatting tool, into our project. Prettier helps us maintain consistent code formatting across the entire codebase, leading to improved code readability and better collaboration among team members.**
1. Added Prettier to the project dependencies in the package.json file.
2. Created a .prettierrc file to define the code formatting rules.
3. Applied Prettier formatting to all applicable files in the project.
4. Set up Husky pre-commit hooks to invoke Prettier before each commit.
> feat: init pretter ✨

- assets/css/join_us.css
> refactor: join_us.css. ✨

- assets/css/privacy.css
> refactor: Privcy.css ✨

- assets/css/signup.css
> refactor:  the signup.css ✨

- contributors/contributor.html
- contributors/style.css
- Added to OS-CODE Preloader for Contributors Page.
> fix: missing preloader on contributors page 🧑🏻‍🏭🛠

- contributors/style.css
- Refractor css file with best practices for Contributors Page.
> refractor: styles of contributors page ✨

- CONTRIBUTING.md
Closes #1386 
I have Added guidelines for The contribution in the Contribution. md file that shows how to do Conventional Commits and how its works
> docs: update the Docs 📃

- login/login.html
Closes #1364
This PR addresses the "View Password" functionality and cursor pointer issue to enhance the user experience. I have successfully added the "View Password" functionality to allow users to reveal entered characters for improved visibility during login. Additionally, I have fixed the cursor pointer issue across the application, ensuring that clickable elements now display the hand icon (pointer) for intuitive user interaction. 🌟💡
Your feedback and review on this PR are much appreciated! Let's provide a more user-friendly and engaging interface for our users. 🙏
https://github.com/OSCode-Community/OSCodeCommunitySite/assets/85815172/ad75e7ef-084e-4571-b50f-5550d6cbdd77
> Password View Feature Added🚀 Fixing "View Password" & Cursor Pointer Issue 🔧🔒

- assets/css/style.css
- index.html
> Added Animations

- 404Error.html
- chapters/chapter.html
- contact/contact.html
- events/events.html
- index.html
- login/login.html
- login/profile.html
- policy/policy.html
- resetpass/resetpass.html
- signup/signup.html
Closes #1402
The purpose of this GitHub issue is to implement AI Assistant navigation functionality to enhance the user experience on our website. The goal is to enable users to interact with the AI assistant using natural language commands to navigate to specific URLs or sections of the website.
**Proposed Changes:**
1. **Update `onCommand` Function:**
In the existing code, we need to modify the `onCommand` function to handle navigation commands received from the AI assistant. The function should be updated to check for the "openURL" command and appropriately navigate the user to the specified URL.
```javascript
onCommand: function (commandData) {
if (commandData && commandData.command === 'openURL') {
if (commandData.target === '_blank') {
window.open(commandData.url, '_newtab' + …
```
> Added navigation through OSCODE copilot

- assets/css/contactform.css
- index.html
> updated contact section

- assets/css/join_us.css
- index.html
Closes #1422
i have added the margin to the buttons
> Marginpaddingset

- index.html
Closes #1420 
i have added the image
> imageadded

- assets/css/services.css
@Vaishnavi-Patil2211 Can you please review it?
solves #1373 
also remove the unwanted margin in cards section
> Our Service page cards section ui improvement

- .github/workflows/lock.yml
Closes #1390 
I implemented a workflow that aims to minimize notifications and enhance the support provided to maintainers. This workflow will automatically lock newly opened issues and provide guidance to contributors.
> Workflow to Reduce Notifications 🚀

- assets/css/services.css
- index.html
@Vaishnavi-Patil2211 Can you please review it?
solves #1408 
And responsive
> Join us section cards improvement

- assets/css/chapter.css
- chapters/chapter.html
Closes #1406 
- [ X] I have linked the PR to the correct issue.
- [ X] I have read the [Contribution Guidelines](https://github.com/OSCode-Community/OSCodeCommunitySite/blob/master/CONTRIBUTING.md)
- [ X] I have built and tested the changes, and they do not break or show any errors.
> FOOTER IS UPDATED AT CHAPTER SECTION

- assets/css/client.css
- Refactor client.css styles to improve the codebase and improved the pagination styles
> refactor: client.css ⚒️✨

- README.md
- Improve documentation by replacing plastic style badges into flat style badges.
> docs: improve badges on documentation 📃

- assets/gallery.html
Closes #1427
i have added footer to the gallery page.
> footeradded

- events/event.css
- refactored the events.css file with best practices
> refactor: events.css with best practices ⚒️✨

- services.html
Closes #1230 
Updated heading in the services file.
> [Feat.] Updated heading in the services file [GSSoC'23]

- assets/css/chapter.css
- Refactor the general styles and improved responsiveness of cards for tablet devices.
> refactor: chapter.css media queries and stylings ⚒️✨

- login/login.js
Closes #1443 
Changes Made:
1. Moved imports to the top of the file for better readability and organization.
2. Replaced var with const or let for variable declarations.
3. Encapsulated the login functionality into separate functions for modularity and reusability.
4. Implemented error handling for login operations to handle possible issues, such as invalid credentials or network errors.
5. Replaced direct DOM manipulation with more concise and reusable code.
> Fix: Improve the Error Handling ⚡

- index.html
Closes #1379
This pull request addresses the styling issues with the contact form in our project and aligns it with the OSCodeCommunity theme for a consistent and visually appealing user experience. The changes made in this pull request include the following:
1. Updated CSS: The existing CSS for the contact form has been revised to match the OSCodeCommunity theme's color scheme, typography, and layout. This ensures that the contact form seamlessly blends with the rest of the website's design.
2. Responsive Design: The contact form is now fully responsive, making it look great on various devices, such as desktops, tablets, and mobile phones. It adapts to different screen sizes, improving usability and accessibility.
3. Form Validation: Form validation has been added to ensure that users …
> Fixed Contact Form Styling According to theme

- firebase/firebase.js
Closes #1441 
- Implement try-catch blocks to handle potential errors during module loading and initialization.
- Use dynamic imports with an asynchronous function to load Firebase modules, allowing for better error handling and more informative error messages.
> fix: Improve error handling. ✨

- services.html
@Vaishnavi-Patil2211 please check this pr
solves #1415 
> Align the resume building cards on center

- contributors/style.js
Closes #1444  
**GitHub Issue Title:** Improve Error Handling and Refactor JavaScript Code for Contributors List
1. **Refactor the JavaScript Code:**
Refactor the existing JavaScript code using `async/await` syntax instead of multiple `.then()` callbacks. This will improve code readability and maintainability.
```javascript
async function getContributors() {
try {
// Existing code with fetch and forEach
} catch (error) {
console.error("Error:", error);
// Additional error handling can be added here
}
}
```
2. **Improve Error Handling:**
Currently, the code lacks sufficient error handling, making it difficult for users to understand what went wrong in case of errors. Implement better error handling by adding a more descriptive error message for failed network requests and unexpected data …
> fix: Refactor the style.js

- 404Error.html
- Revamped the entire 404 page with fresh new look and animations
|||
| :---:|:---:|
|**BEFORE**| ![Screenshot 2023-07-29 at 12-03-01 Error Page](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/92252895/556d4c83-141b-4f20-8d51-1954a833cdb7) |
|**AFTER**| ![Screenshot 2023-07-29 at 11-54-54 Error Page](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/92252895/1a6630c7-a6be-4404-abc3-ff233d08df36) |
> feat: revamp the entire 404 page 🚀✨

- assets/css/counts.css
- Added gradient background effects for cards during hover on OS-CODE Homepage
> feat: gradient background effect during hover for cards on homepage ✨

- assets/css/login.css
- Small revamping for elements and for login button
> feat: revamp login page ✨

- chapters/bit.html
- chapters/css/responsive.css
Closes #1413
This pull request addresses an issue with the OSCode Community website's navbar that caused the text "OSCode" to disappear when scrolling down the page. The problem occurred due to the navbar's CSS configuration, which affected its visibility during scroll events. This pull request introduces a solution that ensures the "OSCode" text remains visible in the navbar even when the user scrolls down the page.
This pull request addresses an issue with the OSCode Community website's navbar that caused the text "OSCode" to disappear when scrolling down the page. The problem occurred due to the navbar's CSS configuration, which affected its visibility during scroll events. This pull request introduces a solution that ensures the "OSCode" text remains visible in the navbar even when …
> Fixed Navbar Scroll Issue - Disappearing "OSCode" Text

- assets/css/override.css
- assets/css/style.css
- index.html
@Vaishnavi-Patil2211 Hey, Can I create all the pr related to issues or at a time only one?
solves #1412 
previous
responsive and aligned properly
> Change footer section icon alignment and responsiveness

- services.html
@Vaishnavi-Patil2211 
solves #1426 
before
after 
> Testimonials Alignment

- assets/css/contact.css
- services.html
@Vaishnavi-Patil2211 
solves #1411 
before
after
> Contact form conflict

- assets/css/contact.css
> fix: improper hover effects on contact us page 🛠️ 

- chapters/chapter.html
- contributors/contributor.html
- events/events.html
- index.html
> feat: redirect empty links to 404 page 🚀 ✨ 

- assets/css/services.css
- services.html
@Vaishnavi-Patil2211 Can you please merge my pr
solves #1463 
remove the horizontal scrollbar and make the page responsive
> make service page responsive

- index.html
Closes #1472
i have added the contact us page and email icon is now visible when we hover on it
> contactusadded

- assets/css/faq.css
> fix: improper shadows and background for faq elements 👷🏻‍♂️🛠️ 

- README.md
> docs: made responsive dark/light theme github logo on documentation ✨ 

- assets/css/about.css
> feat: revamp message us button on contact form 🪄 ✨ 

- contact/contact.html
- index.html
Closes #1480 
https://github.com/OSCode-Community/OSCodeCommunitySite/assets/114687502/0d4d0d3d-d937-4a1d-9f4e-cdbfc5f18f53
@Vaishnavi-Patil2211  done
> push bottom to top is added

- assets/css/override.css
- assets/css/style.css
- contact/contact.html
@Vaishnavi-Patil2211 Can you please review my pr
solves #1461 
before
After
> Contact page conflict with other elements

- assets/css/login.css
- assets/css/signup.css
> Fixed Shadows

- assets/css/join_us.css
- index.html
> Fixed the join us section

- assets/css/join_us.css
Closes #1506
i have added padding for the buttons
> paddingadded

- assets/gallery.html
- chapters/chapter.html
- contact/contact.html
- contributors/contributor.html
- events/events.html
- index.html
- login/login.html
||SAMPLES FROM TWO PAGES|
|:---:|:----:|
| **HOME**| ![home](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/92252895/eb4443cf-2d47-4da3-b019-308a2b0ac61d) |
| **CONTACT**| ![contact](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/92252895/196c73cf-0133-4650-b3ac-9533abe16e76) |
- This feature is in beta stage for all of the major browsers like Firefox, Chrome.
- But for now it can finely work on Mobile Chrome, Safari & Vivaldi Etc.
- The screenshots are taken on Vivaldi Browser for demonstration.
> feat: add nav bar theme feature to entire os-code website 🪄✨ 

- assets/css/join_us.css
https://user-images.githubusercontent.com/92252895/257058577-4e5726f0-c6c2-42c2-b024-ecff39b2dc07.mp4
> feat: generalize hover state gradients for social icons on homepage ✨ 

- contributors/contributor.html
- contributors/style.css
|||
|:---:|:---:|
| **BEFORE**|![before](https://user-images.githubusercontent.com/92252895/257056898-79cd69ae-4bc1-416a-83bd-104f957f2142.png) |
|**AFTER**|![after](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/92252895/0958b442-3926-4345-9109-0309524ff46c) |
> fix: improper heading sizing and background gradient 👷🏻‍♂️⚒️ 

- assets/css/override.css
> feat: revamp faq accordions 🪄✨

- assets/css/faq.css
> fix: incorrect gradient for element on homepage 👷🏻‍♂️⚒️

- events/events.html
Closes #1514
i have added the image when the walkathon is active
> pictureaddedwhenitisactive

- assets/css/about.css
Closes #1512
i have added the hovering effect on the message us button with linear gradient from left to right
> buttonhoveringeffect

- contributors/style.css
Closes #1516 
i have added transformation and I have changed the color of contributors head line also
> contributorstylingshangeed

- chapters/css/styles.css
Closes #1522 
i have added the same height to all the boxes and I have changed the box shadow also
> heightissetcorrectlynow

- assets/css/style.css
- chapters/chapter.html
@Vaishnavi-Patil2211 Can you please review it?
solves #1414 
previous
Now
> fix: Chapter page footer mash up

- assets/css/counts.css
> Fixed the gradient

- assets/css/chapter.css
> fix: uneven sizings of cards on chapters page 🛠️

- login/profile.html
Closes #1447 
In the @keyframes glowing rule, the keyframes at 0% and 100% now share the same style for color, as they both set it to `#ff84c1` This reduces redundancy and improves maintainability.
> fix: Styling of Profile.html ✨

- .github/ISSUE_TEMPLATE/Refactor.yml
- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/documentation.yml
- .github/ISSUE_TEMPLATE/feature_req.yml
Closes #1524
I have Updated the Issue Template that automatically added `gssoc23` label on the issue
> Issue template Updated ✨

- assets/css/events.css
- assets/css/services.css
- assets/css/style.css
- events/event.css
- events/events.html
@Vaishnavi-Patil2211  Can you please review it?
solves #1543 
> Event page navbar toggle button is not visible on mobile view

- assets/css/services.css
@Vaishnavi-Patil2211 Can you please merge it?
solves #1544 
previous
Now
> fix: Service page text is not visible on mobile view

- assets/css/login.css
- login/login.html
Closes #1525 
https://github.com/OSCode-Community/OSCodeCommunitySite/assets/114687502/131f392c-3447-4cfd-9a43-92cb205fdeda
@Vaishnavi-Patil2211 and @Divesh2003 have a look
> button is updated and the removed scroll bar

- .github/workflows/pr-author-assign.yml
> feat: automating author assign pr to author 💡

- assets/css/override.css
- assets/css/style.css
- contributors/contributor.html
Closes #1560
i have added the all social icons in single line in contributor page
> madesociallinksinsingleline

- assets/css/join_us.css
- assets/css/style.css
Closes #1551 
To maintain consistency across the website the changes i made are 
1.  The font size is changed across the home page
2. the font color is changed 
3. Since a dark mode is not implemented on the website, the color scheme has been designed using light colors to maintain a bright and visually appealing appearance.
> home page style changed

- events/events.html
Closes #1571 
The id given was not updated after the section being updated
Now it scroll down to the section
> now it scrolls down to events section

- contributors/style.css
Closes #1564 
Added background animation in contributors page.
> [Feat]Added background animation in contributors page.

- contact/contact.html
Closes #1561 
Updated logo and text overlapping in footer in Contacts Page
> [Bug]:Updated logo and text overlapping in footer in Contacts Page [GSSoC'23]

- assets/css/contact.css
- assets/css/contactform.css
- index.html
Closes #1558
i have changed the contact us section attractive
> assresschanged

- assets/css/style.css
- chapters/css/styles.css
Closes #1556 
i have made the image in chapter at correct place
> addedimageatcorrectplace

- contributors/style.css
Closes #1576 
the changes i made are 
1. background color & added gradient
2. changes text color 
3. added light to dark gradient in cards 
4. remove error from the code
> updated contributor page

- signup/signup.js
Closes #1535
**1. Use named imports for better readability and maintainability.
2. Separate the functions for signup and Google signup for clarity and reusability.
3. Move the input field values retrieval and validation to separate functions.
4. Use more descriptive variable names.
5. Extract the password toggle logic into a function.**
> Refactor JavaScript code for Signup.js ✨

- policy/policy.html
Closes #1577 
Preloder is fixed
> preloader updated

- assets/css/login.css
- assets/css/signup.css
- signup/signup.html
login and sign up page improved
Closes #1573 
before the changes
After Changes
1. i change the background color to improve user experience as the website should feel connected 
2. login button and signup button is made same 
3. refactor the code
4. removed white line spaces from the bottom  of the website
5.
> login and signup page button improved

- assets/css/style.css
Closes #1574 
the button are fixed and are properly working
> overlapping button fixed

- CONTRIBUTING.md
Closes #1540 
I have Improved the contributing.md guide in the easiest way.
> [docs]: Improve contributing.md guide #1540

- assets/css/style.css
> numbers section made responsive {ss added}

- assets/gallery.html
- contributors/contributor.html
- events/events.html
- index.html
Closes #1616 
Logo and name in the footer is not same on different pages.
> Updated footer in all the pages

- contributors/contributor.html
- login/login.html
- signup/signup.html
> Navbar is not same for every page

- login/login.html
- signup/signup.html
> login and signup improvement

- assets/css/style.css
Closes #1628 
https://github.com/OSCode-Community/OSCodeCommunitySite/assets/119532943/b498bd36-7288-4688-a296-ceda686d4362
> our accomplishment section made responsive

- assets/css/privacy.css
- policy/policy.html
> privacy policy header updated

- .github/workflows/auto_issue_assign.yml
- .github/workflows/issue_close_greet.yml
- .github/workflows/issues.yml
- .github/workflows/pr_auto_comment.yml
- .github/workflows/pr_close_greet.yml
- .github/workflows/prevent_multiple_issues.yml
Closes #1550 
- **Added 6 workflows in .github/workflows Folder.**
- **Added Whatever Mentioned in Specific Issue Description except deno.yml File. Because of this File is used for Third-Party License based . So, this is not Fit to Our Requirements.**
- **Instead of deno.tml File, I added pr_close_greet.yml and issue_close_greet.yml Files. This is Very Useful Files.**
- **Kindly taken my Request into Consideration and Add Valid Level Label under GSSOC'23.**
> feat: Added Multiple Workflows in GitHub Workflows Folder

- .github/ISSUE_TEMPLATE/styles.yml
Closes #1549 
- **Added styles.yml File for Raising individual Code style and enhancement of UI in GitHub Issue Templates.**
- **This styles.yml Issue Template is Very Useful Entire Contribution Stages. I hope accepting My PR with add Valid Level Label Under GSSOC'23.**
> feat: Added styles.yml File in GitHub Issue Templates

- assets/gallery.html
- chapters/bit.html
- chapters/chapter.html
- contact/contact.html
- contributors/contributor.html
- events/events.html
- index.html
- login/login.html
- resetpass/resetpass.html
- signup/signup.html
Closes #1531 and #1533 
- **Added ARIA attributes and Social Icons in Suitable HTML Files.**
- **Fixed Typos of title-Tooltip Text in Some HTML Files.**
- **Additionally , Added above Functionalities in Some Missed areas of Respective Files.**
- **I have Mixed Two Issues No:** #1531 and #1533 
- **Because of Similar Functionalities are needs to Add Most of the Areas.**
- **Kindly Taken My Humble Request into Consideration and Add Valid Level Label under GSSOC'23. Why Because of I am worked on Almost All HTML Files.**
> fix: Added ARIA attributes and Other attributes in Suitable 10 HTML Files

- assets/css/style.css
Closes #1634 
https://github.com/OSCode-Community/OSCodeCommunitySite/assets/119532943/10e7b8c7-bff9-4100-bc11-f91935ceba70
> box shadow added on back to top only on hovering
