OSCode-Community/OSCodeCommunitySite

chapters/chapter.html
events/events.html

- On clicking Chapters position of 'Blogs' and 'Chapters' is changing.
- On clicking Events it's disappearing from the navbar when we're on the Events page.
Updated Both the page's navbar as follows - 
**At Home -**
- Before & After-
**On the Chapters Page -**
- Before - 
- After -
**On the Events Page -**
- Before - 
- After -

Updated Navbar of Chapters and Events Page

---

chapters/chapter.html
events/events.html

- On clicking Chapters position of 'Blogs' and 'Chapters' is changing.
- On clicking Events it's disappearing from the navbar when we're on the Events page.
Updated Both the page's navbar as follows - 
**At Home -**
- Before & After-
**On the Chapters Page -**
- Before - 
- After -
**On the Events Page -**
- Before - 
- After -

Updated Navbar of Chapters and Events Pages

---

events/events.html

This PR adresses the issue #136. 
This PR fixes the bug in the events page where the embedded link in the logo was incorrect.
Changes made:
Changes made in .\events\events.html
Testing: 
The link is now working by pressing the logo on the events page.
PFA the image which displays the link on the bottom left when hovered over the logo
@akshathar-navada Please let me know if there is any discrepancy. I have tried making the PR according to the code of conduct. Thankyou.

Solved issue #136: Fixed embedded link in logo bug [GSSOC'23]

---

chapters/chapter.html

Earlier in the Chapters Page, the college names were clickable, clicking which opened the same page in a new tab, converted this to non-clickable.
This PR fixes #317 
Thanks for assigning me this issue.

Made the college name non-clickable

---

assets/css/style.css

*The webpage was having a responsiveness issue. In mobile sizes (specifically Samsung Galaxy S20 Ultra 412\*915) the text was overflowing out of some of the containers. Now, it is working perfectly fine*
This PR fixes #432 
##Before 
https://github.com/OSCode-Community/OSCodeCommunitySite/assets/104912087/de289751-aea1-4fd3-b47a-99e892e81774
**Thank you sir for giving me this opportunity**

[testimonial item class] Responsiveness Issue of text overflowing out of the placards solved

---

index.html

corrected the about us link in the footer section under community header. Now when the user clicks on the About us this will navigate to the about us(who we are )  section.
This PR fixes #453 
Now we can navigate to about us section by clicking the about us in the footer under the community section.

About us is updated to navigate to about us section

---

assets/css/style.css
index.html

This PR fixes #474 
The hover effects of all socials icons have been changed.

Change hover effect of all socials icons

---

assets/css/contact.css
assets/css/style.css
index.html

We are able to see the questions which makes it more accessible for users.
This PR fixes issue #494 
Before clicking on the drop-down:
After clicking on the drop_down:

Change in FAQS #494

---

assets/css/style.css

Improve after footer extra space.
Closes #583 
There was some extra space after footer
Previous Image:
After modification image:
This issue is resolved from my side, I think contributors should view other issues.

Updated style.css

---

assets/css/style.css

Transition for 'Testimonials' section
Closes #587 
When we hover out, the transition is fixed now
https://github.com/OSCode-Community/OSCodeCommunitySite/assets/101629997/45fd2f76-8a45-45ee-8e5f-8898f094d2a8
- My cursor did not show up in the video but it is working

Updating transition for 'Testimonials' Section

---

index.html

Closes #709 
- Added `aria-label` attribute for social anchors like github & twitter
- The `aria-label` attribute is important for screen readers because it provides a text label for an object, such as `a` with social icons. When a screen reader encounters the object, the `aria-label` text is read so that the user will know what it is. 
- This is important for people who are blind or have low vision, as they rely on screen readers to access the web.
- Improved `title` attribute's data, because the title attribute is intended to provide additional information to screen reader users.
- And along with that i added `rel` for the anchors which are lacking them to ensure best practices for crawlers
- Because adding the `rel="noopener noreferrer"` attribute can help to protect this website from …

💡 [FEAT]: ACCESSIBLE SOCIAL ANCHORS FOR FOOTER W/ A11Y PRINCIPLES

---

.vscode/settings.json
assets/css/contactform.css
index.html

In Contact form the labels moves up when input is focused
Closes #729 
In this pull request, I've elevated the user experience of our contact form by implementing a delightful vertical transition effect that gracefully enhances input focus. By modifying both the contactform.css and index.html files, I've achieved the desired changes, ensuring a visually pleasing and engaging interface for our users.

[GSSoC'23]:Have given the vertical translation effect to the labels in contact form #729

---

contributors/style.css

Closes #1091
in have changed the button styling when we hover on it and not hovering on it.

button style change

---

assets/css/gallery.css

- Fixed the image disortion happened for images on gallery page, and linted the css too.
|||
| :---: | :----: |
| **BEFORE**  | ![Screenshot 2023-07-22 at 12-35-37 OS-CODE Events](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/92252895/4c03c57d-8554-4387-a77d-e7b1caa88be2) |
| **AFTER** | ![Screenshot 2023-07-22 at 12-36-31 OS-CODE Events](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/92252895/d0e67ef0-ae34-4d6f-a215-0674afbbf1a6) |

fix: image disortion on gallery page 🛠

---

chapters/css/styles.css

Closes #1157
i have changed the meet os team styling the image gets bigger when we hover on it and box shadow I have changed

meetteamstyling

---

chapters/chapter.html

- This PR is about fixing the broken source links of images for Institutes on `chapter.html` page
https://github.com/OSCode-Community/OSCodeCommunitySite/assets/92252895/b235749b-3a08-4536-9f42-94f4bd03e9ef

fix: broken images links for institutes on chapter page 🛠

---

contributors/contributor.html
contributors/style.css

Closes #1158
i have changed the navbar color before it was mixed with white and also in the footer of contributor page the white space is removed

navbarandfooterchanged

---

assets/css/style.css

- Fixes the incorrect alignment of heading and os-code logo on footer to improve UI.
|||
|:----:|:----:|
|![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/92252895/7e761ba1-14a0-4941-9985-1767e8787328) | ![Screenshot 2023-07-24 at 22-35-00 OS Code](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/92252895/f2fa89bd-6c0b-48c7-952f-540b5e0fa611)

fix: incorrect alignment of footer logo and os code name 🛠

---

events/events.html

Closes #1187 
I have added the tooltip on the events page also I have changed the color of WhatsApp to green before it was blue which was a bug

eventpagefootersocialicons

---

login/login.html

- Added the contributors navigational link to the login page's nav bar for proper navigation.

fix: lack of contributors link on login page 🛠

---

contact/contact.html

Closes #1262
i have made the footer logo and the social links in horizontal row before they were in vertical row

madefooterincorrectplace

---

index.html

Closes #1282 
[screen-capture.webm](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/85815172/700d51df-9d26-4174-b1f1-0827679ab1ed)

fix: Placeholder Collapsing 🎉

---

assets/css/login.css

- Fixed the space consuming button by refactoring the styles of button by replacing the `border` with `outline` to prevent consuming extra space.
https://github.com/OSCode-Community/OSCodeCommunitySite/assets/92252895/678f5496-7327-4d44-8248-3be9ed98378e

fix: space consuming border bug with button on login page 🧑🏻‍🏭🛠

---

assets/css/client.css

- This PR fixes the broken brand logo image carousal effect on Sponsers section of OS-CODE Homepage

fix: broken brand logo image carousal effect on homepage 🧑🏻‍🏭🛠

---

chapters/chapter.html

- Added `aria-label` attribute for social anchors like github & twitter
- The `aria-label` attribute is important for screen readers because it provides a text label for an object, such as `a` with social icons. When a screen reader encounters the object, the `aria-label` text is read so that the user will know what it is. 
- This is important for people who are blind or have low vision, as they rely on screen readers to access the web.
- Improved `title` attribute's data, because the title attribute is intended to provide additional information to screen reader users.
- And along with that i added `rel` for the anchors which are lacking them to ensure best practices for crawlers
- Because adding the `rel="noopener noreferrer"` attribute can help to protect this website from security …

feat: made social anchors accessible 🚀

---

index.html

- Fixed the wrong navigational link of Events page on OS-CODE Website

fix: wrong navigational link for events page 🛠

---

assets/css/style.css

- This PR fixes the cutted of cards by adding appropriate styles rules in order to prevent the card from being cutting of.
|BEFORE|AFTER|
|:---:|:----:|
| ![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/92252895/ab1a6a5f-7dd6-4661-b1f0-3ffdfe03bf2a) | ![image](https://github.com/OSCode-Community/OSCodeCommunitySite/assets/92252895/64107022-e10a-4a07-8a6b-601980260efd) |

fix: card cut-off on events page 🛠

---

assets/css/counts.css

Closes #1369
To refactor the CSS code, we can clean it up, organize it, and make it more maintainable. Here's the refactored version:
```css
/* --------------------------------------------------------------
-------------------------------------------------------------- */
hr.line {
border: 4px solid var(--backtotop-btn-color);
border-radius: 5px;
width: 120px;
opacity: 1;
}
.counts {
padding-top: 80px;
}
#counts h1 {
color: white;
font-family: "Montserrat", sans-serif;
font-size: 40px;
font-weight: bold;
text-align: center;
}
.count-box {
padding: 30px 30px 25px 30px;
width: 100%;
position: relative;
text-align: center;
box-shadow: 0px 2px 5px slateblue;
border-radius: 10px;
cursor: pointer;
transition: 0.4s all ease-in-out;
}
.count-box:hover {
transform: scale(1.1);
}
.count-box > span …
```

fix: refactor the counts.css ✨  

---

assets/css/resetpass.css

Closes #1382
**Description:**
Currently, the CSS code for the reset password page contains some redundant and unnecessary properties that can be refactored to improve readability and maintainability. The goal of this issue is to refactor the existing CSS code for the reset password page to make it cleaner and more efficient.
**Refactor Plan:**
1. Remove unnecessary units on `padding` for `.resetpass-box`.
2. Remove unnecessary `margin-top` value from `.resetpasstxt`.
3. Remove duplicate `width: 100%;` from `.form-container`.
4. Remove unnecessary `position: relative;` from `.form-container .user-box`.
5. Remove `background: transparent;` from `.form-container .user-box input` as it is not needed.
6. Remove `flex-grow: 1;` from `.form-container .name-part` as it doesn't seem to be used.
7. …

Refactor:  Restart-Password.CSS ✨

---

assets/css/resetpass.css
resetpass/resetpass.html
resetpass/resetpass.js

Closes #1393
Add empty validation on passwords
Error message shown below of each fields.
@Vaishnavi-Patil2211 issue#1393 resolved!!

Validation added on reset password form

---

.github/ISSUE_TEMPLATE/Refactor.yml

fix: wrong repository navigation link on refactor issue template 🛠️
